students/kyte/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :users, path: '/admin/users'
  resources :boilerplates
  resources :repositories
  resources :projects

  mount Sidekiq::Web => '/sidekiq'

  get 'project_view', to: 'projects#project_view', as: :project_view

  get 'repository_view', to: 'projects#repository_view', as: :repository_view

  post 'repository/add_member', to: 'repositories#add_member', as: :add_member

  delete 'repository/remove_member', to: 'repositories#remove_member', as: :remove_member

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"

  devise_for :users do
  end
end

students/kyte/app/models/boilerplate.rb
class Boilerplate < ApplicationRecord
end

students/kyte/app/controllers/boilerplates_controller.rb
class BoilerplatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_boilerplate, only: %i[ show edit update destroy ]

  # GET /boilerplates or /boilerplates.json
  def index
    @boilerplates = Boilerplate.all
  end

  # GET /boilerplates/1 or /boilerplates/1.json
  def show
  end

  # GET /boilerplates/new
  def new
    @boilerplate = Boilerplate.new
  end

  # GET /boilerplates/1/edit
  def edit
  end

  # POST /boilerplates or /boilerplates.json
  def create
    @boilerplate = Boilerplate.new(boilerplate_params)

    respond_to do |format|
      if @boilerplate.save
        format.html { redirect_to boilerplate_url(@boilerplate), notice: "Boilerplate was successfully created." }
        format.json { render :show, status: :created, location: @boilerplate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @boilerplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boilerplates/1 or /boilerplates/1.json
  def update
    respond_to do |format|
      if @boilerplate.update(boilerplate_params)
        format.html { redirect_to boilerplate_url(@boilerplate), notice: "Boilerplate was successfully updated." }
        format.json { render :show, status: :ok, location: @boilerplate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @boilerplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boilerplates/1 or /boilerplates/1.json
  def destroy
    @boilerplate.destroy

    respond_to do |format|
      format.html { redirect_to boilerplates_url, notice: "Boilerplate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boilerplate
      @boilerplate = Boilerplate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def boilerplate_params
      params.require(:boilerplate).permit(:name, :git_link)
    end
end

students/kyte/app/helpers/boilerplates_helper.rb
module BoilerplatesHelper
end

students/kyte/app/views/boilerplates/_boilerplate.html.erb
<div id="<%= dom_id boilerplate %>" class="boilerplate">
  <p>
    <strong>Name:</strong>
    <%= boilerplate.name %>
  </p>

  <p>
    <strong>Git link:</strong>
    <a href="<%= boilerplate.git_link %>"><%= boilerplate.git_link %></a>
  </p>

  <p>
    <%= link_to "Show this boilerplate", boilerplate %>
  </p>

</div>

students/kyte/app/views/boilerplates/_form.html.erb
<%= bootstrap_form_with(model: boilerplate) do |form| %>
  <% if boilerplate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(boilerplate.errors.count, "error") %> prohibited this boilerplate from being saved:</h2>

      <ul>
        <% boilerplate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name %>
  </div>

  <div id="git-link">
    <%= form.url_field :git_link, placeholder: "https://github.com/example", pattern: "https(:\/\/)(github|gitlab).*"%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

students/kyte/app/views/boilerplates/edit.html.erb
<h1>Editing boilerplate</h1>

<%= render "form", boilerplate: @boilerplate %>

<br>

<div>
  <%= link_to "Show this boilerplate", @boilerplate %> |
  <%= link_to "Back to boilerplates", boilerplates_path %>
</div>

students/kyte/app/views/boilerplates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Boilerplates</h1>

<div id="boilerplates">
  <% @boilerplates.each do |boilerplate| %>
    <%= render boilerplate %>
  <% end %>
</div>

<%= link_to "New boilerplate", new_boilerplate_path %>

students/kyte/app/views/boilerplates/new.html.erb
<h1>New boilerplate</h1>

<%= render "form", boilerplate: @boilerplate %>

<br>

<div>
  <%= link_to "Back to boilerplates", boilerplates_path %>
</div>

students/kyte/app/views/boilerplates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @boilerplate %>

<div>
  <%= link_to "Edit this boilerplate", edit_boilerplate_path(@boilerplate) %> |
  <%= link_to "Back to boilerplates", boilerplates_path %>

  <%= button_to "Destroy this boilerplate", @boilerplate, method: :delete %>
</div>