students/kyte/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :users, path: '/admin/users'
  resources :boilerplates
  resources :repositories
  resources :projects

  mount Sidekiq::Web => '/sidekiq'

  get 'project_view', to: 'projects#project_view', as: :project_view

  get 'repository_view', to: 'projects#repository_view', as: :repository_view

  post 'repository/add_member', to: 'repositories#add_member', as: :add_member

  delete 'repository/remove_member', to: 'repositories#remove_member', as: :remove_member

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"

  devise_for :users do
  end
end

students/kyte/app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [500, 500]
  end

  has_many :repositories
  has_many :users, through: :repositories
end

students/kyte/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_project, only: %i[ show edit update destroy project_view repository_view ]

  # GET /projects or /projects.json
  def index
    @foo = "bar"
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  def project_view
    render turbo_stream:
      turbo_stream.replace('right-frame',
        partial: 'project_view',
        locals: { project: @project }
      )
  end

  def repository_view
    @repository = Repository.find(params[:repository_id])
    render turbo_stream:
      turbo_stream.replace('right-frame',
        partial: 'repository_view',
        locals: { repository: @repository }
      )
  end

  def repository_new
    @repository = Repository.new
    @project = Project.find(params[:project_id])
    @repository.project = @project

    render turbo_stream:
      turbo_stream.replace('right-frame',
        partial: 'repository_new',
        locals: { repository: @repository }
      )
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :avatar)
    end
end

students/kyte/app/helpers/projects_helper.rb
module ProjectsHelper
end

students/kyte/app/views/projects/_form.html.erb
<%= bootstrap_form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.file_field :avatar, accept: 'image/png, image/jpeg' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

students/kyte/app/views/projects/_members.erb
<turbo-frame id="members-frame">
  <%= bootstrap_form_with(url: "repository/add_member") do |form| %>
    <%= form.hidden_field :repository_id, value: repository.id %>
    <%= form.select :user_id, options_for_select(User.all_outside_repository(repository.id).map { |u| [u.name, u.id] }) %>
    <%= form.submit "Add member" %>
  <% end %>

  <ul>
    <% members.each do |member| %>
      <li>
        <%= member.name %>
        <%= button_to "Remove", remove_member_path(repository_id: repository, user_id: member), method: :delete %>
      </li>
    <% end %>
  </ul>
</turbo-frame>

students/kyte/app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="project-cell">
<img id="img" src="<%= (url_for(project.avatar)) %>">
<div id="info-column">
  <p id="title">
    <strong>Title:</strong>
    <%= project.title %>
  </p>
  <p id="edit">
    <%= link_to "Show this project", project_view_path(id: project.id) %>
  </p>
</div>
</div>

students/kyte/app/views/projects/_project_view.erb
<turbo-frame id="right-frame">
    <% if @project %>
        <div>
            <h2><%= @project.title %></h2>
        </div>
        <div>
          <%= link_to "Edit", edit_project_path(@project) %>
          <%= link_to "New Repository", new_repository_path(:project_id => @project) %>
          <%= button_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
        <div class="repositories">
          <h3>Repositories</h3>
          <% @project.repositories.each do |repository| %>
            <div>
              <p><b>Repository:</b> <%= repository.title %>
              </p>
              <p>
                <a href="<%= repository.remote_url %>">git</a>
                <%= link_to "View", repository_view_path(id: @project.id, repository_id: repository.id) %></p>
              </p>
            </div>
          <% end %>
        </div>
    <% end %>
</turbo-frame>

students/kyte/app/views/projects/_repository_new.erb
<turbo-frame id="right-frame">
  <h1>New repository</h1>

  <%= render "form", repository: @repository %>

  <br>

  <div>
    <%= link_to "Back to repositories", repositories_path %>
  </div>
</turbo-frame>

students/kyte/app/views/projects/_repository_view.html.erb
<turbo-frame id="right-frame">
  <h2>Repository</h2>
  <%= @repository.name %>
  <br />
  <%= link_to "Show project", project_view_path(id: @project.id) %>
  <%= button_to "Delete", repository_path(@repository), method: :delete, data: { confirm: "Are you sure?" } %>
  <a href="<%= @repository.remote_url %>" target="_blank">Remote</a>

  <div>
    <h3>Members</h3>

    <%= render partial: "members", locals: { repository: @repository, members: @repository.users } %>
  </div>
</turbo-frame>

students/kyte/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<p>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</p>

students/kyte/app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div class="row">
  <div class="col-md-4">
    <div id="projects">
      <% @projects.each do |pro| %>
        <%= render pro %>
      <% end %>
      <p id="new-link">
        <%= link_to "New project", new_project_path %>
      </p>
    </div>
  </div>
  <div class="col-md-8">
    <%= render 'project_view', locals: { project: @project } %>
  </div>
</div>

students/kyte/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div id="back-projects">
  <%= link_to "Back to projects", projects_path %>
</div>

students/kyte/app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>