students/kyte/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :users, path: '/admin/users'
  resources :boilerplates
  resources :repositories
  resources :projects

  mount Sidekiq::Web => '/sidekiq'

  get 'project_view', to: 'projects#project_view', as: :project_view

  get 'repository_view', to: 'projects#repository_view', as: :repository_view

  post 'repository/add_member', to: 'repositories#add_member', as: :add_member

  delete 'repository/remove_member', to: 'repositories#remove_member', as: :remove_member

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"

  devise_for :users do
  end
end

students/kyte/app/models/repository.rb
# module Gitlab
# def self.create_project(name)
# object = Object.new
# def object.id
# 123
# end
# object
# end
# end

class Repository < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :project
  belongs_to :boilerplate

  before_save :create_gilab_project

  after_create :fill_project_with_boilerplate

  after_destroy :delete_project

  def add_team_member(user)
    Gitlab.add_team_member(remote_id, user.gitlab_id, 40)

    users << user
  end

  def remove_team_member(user)
    Gitlab.remove_team_member(remote_id, user.gitlab_id)

    users.delete(user)
  end

  def remote_project
    Gitlab.project(@remote_id)
  end

  def delete_project
    Gitlab.delete_project(remote_id)
  end

  private

  def create_gilab_project
    project = Gitlab.create_project(name)
    self.remote_id = project.id
    self.remote = project.ssh_url_to_repo
    self.remote_url = project.http_url_to_repo
  end

  def fill_project_with_boilerplate
    FillRepositoryJob.perform_async(id)
  end
end

students/kyte/app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_repository, only: %i[ show edit update destroy ]

  # GET /repositories or /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1 or /repositories/1.json
  def show
  end

  def add_member
    @repository = Repository.find(params[:repository_id])
    @user = User.find(params[:user_id])

    @repository.add_team_member(@user)

    redirect_to repository_view_path(:id => @repository.project_id, :repository_id => @repository.id)
  end

  def remove_member
    @repository = Repository.find(params[:repository_id])
    @user = User.find(params[:user_id])

    @repository.remove_team_member(@user)

    redirect_to repository_view_path(:id => @repository.project_id, :repository_id => @repository.id)
  end

  # GET /repositories/new
  def new
    @repository = Repository.new

    render turbo_stream:
      turbo_stream.replace('right-frame',
        template: 'repositories/new',
        locals: { repository: @repository }
      )
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories or /repositories.json
  def create
    @repository = Repository.new(repository_params)
# @repository.user = current_user

    respond_to do |format|
      if @repository.save
        format.html { redirect_to repository_url(@repository), notice: "Repository was successfully created." }
        format.json { render :show, status: :created, location: @repository }
        format.turbo_stream do
          redirect_to project_view_path(:id => @repository.project_id)
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1 or /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to repository_url(@repository), notice: "Repository was successfully updated." }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1 or /repositories/1.json
  def destroy
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to repositories_url, notice: "Repository was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream do
        redirect_to project_view_path(:id => @repository.project_id)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def repository_params
      params.require(:repository).permit(:title, :name, :boilerplate_id, :project_id)
    end
end

students/kyte/app/helpers/repositories_helper.rb
module RepositoriesHelper
end

students/kyte/app/views/repositories/_form.html.erb
<%= bootstrap_form_with(model: repository) do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :project_id, value: params[:project_id] %>

  <% if repository.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
        <% repository.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.select :boilerplate_id, options_from_collection_for_select(Boilerplate.all, :id, :name) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

students/kyte/app/views/repositories/_repository.html.erb
<div id="<%= dom_id repository %>">
  <p>
    <strong>Title:</strong>
    <%= repository.title %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= repository.name %>
  </p>

</div>

students/kyte/app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Show this repository", @repository %> |
  <%= link_to "Back to repositories", repositories_path %>
</div>

students/kyte/app/views/repositories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Repositories</h1>

<div id="repositories">
  <% @repositories.each do |repository| %>
    <%= render repository %>
    <p>
      <%= link_to "Show this repository", repository %>
    </p>
  <% end %>
</div>

<%= link_to "New repository", new_repository_path %>

students/kyte/app/views/repositories/new.html.erb
<turbo-frame id="right-frame">
<h1>New repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Back to repositories", repositories_path %>
</div>
</turbo-frame>

students/kyte/app/views/repositories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @repository %>

<div>
  <%= link_to "Edit this repository", edit_repository_path(@repository) %> |
  <%= link_to "Back to repositories", repositories_path %>

  <%= button_to "Destroy this repository", @repository, method: :delete %>
</div>